// <auto-generated />
using System;
using BackEnd.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BackEnd.Migrations
{
    [DbContext(typeof(GrafisTestContext))]
    [Migration("20210128225915_First Migration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("BackEnd.Models.Client", b =>
                {
                    b.Property<long>("IdClient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<string>("EmailClient")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("NameClient")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("IdClient");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("BackEnd.Models.Product", b =>
                {
                    b.Property<long>("IdProduct")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<string>("DescriptionProduct")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ImgPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameProduct")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<float>("ValueProduct")
                        .HasColumnType("real");

                    b.HasKey("IdProduct");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("BackEnd.Models.Request", b =>
                {
                    b.Property<long>("IdRequest")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<DateTime>("DateRequest")
                        .HasColumnType("datetime2");

                    b.Property<float>("DiscountRequest")
                        .HasColumnType("real");

                    b.Property<int>("IdClient")
                        .HasColumnType("int");

                    b.Property<int>("NumberRequest")
                        .HasColumnType("int");

                    b.Property<float>("TotalValue")
                        .HasColumnType("real");

                    b.Property<float>("ValueRequest")
                        .HasColumnType("real");

                    b.HasKey("IdRequest");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("BackEnd.Models.RequestProduct", b =>
                {
                    b.Property<long>("IdProduct")
                        .HasColumnType("bigint");

                    b.Property<long>("IdRequest")
                        .HasColumnType("bigint");

                    b.Property<int>("QuantityProduct")
                        .HasColumnType("int");

                    b.HasKey("IdProduct", "IdRequest");

                    b.HasIndex("IdRequest");

                    b.ToTable("RequestProducts");
                });

            modelBuilder.Entity("BackEnd.Models.RequestProduct", b =>
                {
                    b.HasOne("BackEnd.Models.Product", "Product")
                        .WithMany("RequestProducts")
                        .HasForeignKey("IdProduct")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEnd.Models.Request", "Request")
                        .WithMany("RequestProducts")
                        .HasForeignKey("IdRequest")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("BackEnd.Models.Product", b =>
                {
                    b.Navigation("RequestProducts");
                });

            modelBuilder.Entity("BackEnd.Models.Request", b =>
                {
                    b.Navigation("RequestProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
